%%%-----------------------------------------------------------------------------
%%% @doc       MQT GUI table schema descriptor
%%% @author    Serge Aleynikov <saleyn@gmail.com>
%%% @copyright 2015 MQT, LLC. All rights reserved.
%%% @end
%%%-----------------------------------------------------------------------------
%%% Created: 2015-11-16 19:08:56
%%%-----------------------------------------------------------------------------
%%%
%%% This file is automatically generated by code_gen.es
%%% from ../spec/tfx_tables.xml
%%%
%%%            >>>>>>>  !!! DO NOT MODIFY BY HAND  !!! <<<<<<<<
%%%
%%%-----------------------------------------------------------------------------
-module(tfx_schema).

-export([
      tables/0, is_schema/1, proto_xml/0, table_arity/1, table_fields/1
]).

-include("tfx_schema.hrl").

%% @doc List of tables
-spec tables() -> [{Table::atom(), Options::list()}].
tables() ->
    [].

table_arity(secdef2) -> 1;
table_arity(secdef)  -> 24;
table_arity(T)       -> throw({undefined_table, T}).

table_fields(secdef2) -> [symbol];
table_fields(secdef)  -> [key,
                          instr,
                          secid,
                          xchg_secid,
                          isin,
                          descr,
                          ccy,
                          settl_ccy,
                          contr_mult,
                          und_symbol,
                          und_instr,
                          und_secid,
                          und_xchg_secid,
                          maturity,
                          strike,
                          init_mgn_buy,
                          init_mgn_sell,
                          init_mgn_synth,
                          status,
                          address,
                          px_step,
                          px_lo_lim,
                          px_hi_lim];
table_fields(T)      -> throw({undefined_table, T}).

is_schema(secdef) -> true;
is_schema(_)      -> false.

proto_xml() ->
<<"<protocol app=\"tfx\" version=\"1.0\" descr=\"TFX RPC protocol\">
  <schema name=\"secdef\" descr=\"Security Definition\" insert=\"true\" update=\"true\" delete=\"true\">
    <field name=\"xchg\" type=\"atom\" len=\"10\" title=\"Exchange\" descr=\"Exchange name\" key=\"true\" required=\"true\"/>
    <field name=\"symbol\" type=\"atom\" len=\"12\" title=\"Symbol\" descr=\"Internal name of the security\" key=\"true\" required=\"true\"/>
    <field name=\"instr\" type=\"binary\" len=\"12\" title=\"Instr\" descr=\"Exch-specific instrument name\" required=\"true\"/>
    <field name=\"secid\" type=\"long\" title=\"SecID\" descr=\"Security ID\" required=\"true\"/>
    <field name=\"xchg_secid\" type=\"long\" title=\"ExchSecID\" descr=\"Exch-specific Security ID\" required=\"true\"/>
    <field name=\"isin\" type=\"string\" len=\"12\" title=\"ISIN\" descr=\"ISIN security code\" required=\"true\"/>
    <field name=\"descr\" type=\"string\" len=\"80\" title=\"Description\" descr=\"Description\" default=\"\"/>
    <field name=\"ccy\" type=\"atom\" len=\"3\" title=\"Ccy\" descr=\"Base currency\" required=\"true\"/>
    <field name=\"settl_ccy\" type=\"atom\" len=\"3\" title=\"SettlCcy\" descr=\"Settlement currency\" required=\"true\"/>
    <field name=\"contr_mult\" type=\"double\" title=\"ContractMult\" descr=\"Contract multiplier\" required=\"true\" display-format=\"{0:F2}\"/>
    <field name=\"und_symbol\" type=\"atom\" len=\"12\" title=\"UndSymbol\" descr=\"Underlying Internal name of the security\" default=\"undefined\"/>
    <field name=\"und_instr\" type=\"binary\" len=\"12\" title=\"UndInstr\" descr=\"Underlying Exch-specific instrument name\" default=\"undefined\"/>
    <field name=\"und_secid\" type=\"long\" title=\"UndSecID\" descr=\"Underlying Security ID\" default=\"0\"/>
    <field name=\"und_xchg_secid\" type=\"long\" title=\"UndExchSecID\" descr=\"Underlying Exch-specific Security ID\" default=\"0\"/>
    <field name=\"maturity\" type=\"datetime\" title=\"Maturity\" descr=\"Maturity Date\" default=\"0\"/>
    <field name=\"strike\" type=\"double\" title=\"StrikePrice\" descr=\"Strike price in ccy\" default=\"0\"/>
    <field name=\"init_mgn_buy\" type=\"double\" title=\"InitMgnBuy\" descr=\"Initial buy side margin\" display-format=\"{0:F2}\" default=\"0\"/>
    <field name=\"init_mgn_sell\" type=\"double\" title=\"InitMgnSell\" descr=\"Initial sell side margin\" display-format=\"{0:F2}\" default=\"0\"/>
    <field name=\"init_mgn_synth\" type=\"double\" title=\"InitMgnSynth\" descr=\"Initial synthetic margin\" display-format=\"{0:F2}\" default=\"0\"/>
    <field name=\"status\" type=\"char\" title=\"Status\" descr=\"Trading status\" default=\"D\">
            <value code=\"D\" display=\"Disabled\"/>
            <value code=\"E\" display=\"Error\"/>
            <value code=\"S\" display=\"Suspended\"/>
            <value code=\"H\" display=\"Halted\"/>
            <value code=\"T\" display=\"Trading\"/>
        </field>
    <field name=\"address\" type=\"string\" len=\"25\" title=\"Address\" descr=\"Multicast address for change notifications\" default=\"\"/>
    <field name=\"px_step\" type=\"double\" title=\"PriceStep\" descr=\"Minimum price step\" required=\"true\"/>
    <field name=\"px_lo_lim\" type=\"double\" title=\"PriceLoLimit\" descr=\"Price low limit\" default=\"0\"/>
    <field name=\"px_hi_lim\" type=\"double\" title=\"PriceHiLimit\" descr=\"Price high limit\" default=\"0\"/>
  </schema>
  </protocol>">>.
