function hello(text) {
  alert(WAVE.strDefault(text, "Hello"));
}

function render(root, ctx){
var ljs_useCtx = WAVE.isObject(ctx);
var ljs_1 = document.createElement('div');
ljs_1.addEventListener('click', function() { console.log('kaka') }, false);
var ljs_2 = document.createElement('div');
var ljs_3 = "title";
ljs_3 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_3, ctx) : WAVE.strEscapeHTML(ljs_3);
ljs_2.setAttribute('class', ljs_3);
var ljs_4 = "alert('just data')";
ljs_4 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_4, ctx) : WAVE.strEscapeHTML(ljs_4);
ljs_2.setAttribute('data-alert', ljs_4);
var ljs_5 = "<script>alert(\"script\")</script>";
ljs_5 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_5, ctx) : WAVE.strEscapeHTML(ljs_5);
ljs_2.setAttribute('data-alert-script', ljs_5);
ljs_1.appendChild(ljs_2);
var ljs_6 = document.createElement('div');
var ljs_7 = "rate";
ljs_7 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_7, ctx) : WAVE.strEscapeHTML(ljs_7);
ljs_6.setAttribute('id', ljs_7);
ljs_1.appendChild(ljs_6);
var ljs_8 = document.createElement('div');
var ljs_9 = "@color@";
ljs_9 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_9, ctx) : WAVE.strEscapeHTML(ljs_9);
ljs_8.setAttribute('class', ljs_9);
ljs_1.appendChild(ljs_8);
var ljs_10 = document.createElement('div');
var ljs_11 = "stub @color@";
ljs_11 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_11, ctx) : WAVE.strEscapeHTML(ljs_11);
ljs_10.setAttribute('class', ljs_11);
ljs_1.appendChild(ljs_10);
var ljs_12 = document.createElement('div');
var ljs_13 = "<script>alert(\"'<script>alert();</script>'text\")</script>";
ljs_13 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_13, ctx) : WAVE.strEscapeHTML(ljs_13);
ljs_12.innerText = ljs_13;
ljs_1.appendChild(ljs_12);
var ljs_14 = document.createElement('div');
var ljs_15 = document.createElement('div');
var ljs_16 = "@color@";
ljs_16 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_16, ctx) : WAVE.strEscapeHTML(ljs_16);
ljs_15.setAttribute('class', ljs_16);
var ljs_17 = document.createElement('div');
var ljs_18 = document.createElement('div');
var ljs_19 = "@color@";
ljs_19 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_19, ctx) : WAVE.strEscapeHTML(ljs_19);
ljs_18.setAttribute('class', ljs_19);
var ljs_20 = document.createElement('div');
var ljs_21 = document.createElement('div');
var ljs_22 = "@color@";
ljs_22 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_22, ctx) : WAVE.strEscapeHTML(ljs_22);
ljs_21.setAttribute('class', ljs_22);
var ljs_23 = document.createElement('div');
var ljs_24 = document.createElement('div');
var ljs_25 = "@color@";
ljs_25 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_25, ctx) : WAVE.strEscapeHTML(ljs_25);
ljs_24.setAttribute('class', ljs_25);
var ljs_26 = document.createElement('div');
ljs_24.appendChild(ljs_26);
ljs_23.appendChild(ljs_24);
ljs_21.appendChild(ljs_23);
ljs_20.appendChild(ljs_21);
ljs_18.appendChild(ljs_20);
ljs_17.appendChild(ljs_18);
ljs_15.appendChild(ljs_17);
ljs_14.appendChild(ljs_15);
ljs_1.appendChild(ljs_14);
var ljs_27 = document.createElement('div');
var ljs_28 = "@height@";
ljs_28 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_28, ctx) : WAVE.strEscapeHTML(ljs_28);
ljs_27.setAttribute('data-height', ljs_28);
var ljs_29 = "@color@";
ljs_29 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_29, ctx) : WAVE.strEscapeHTML(ljs_29);
ljs_27.setAttribute('class', ljs_29);
ljs_1.appendChild(ljs_27);
var ljs_30 = document.createElement('div');
var ljs_31 = "controls";
ljs_31 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_31, ctx) : WAVE.strEscapeHTML(ljs_31);
ljs_30.setAttribute('id', ljs_31);
var ljs_32 = document.createElement('input');
var ljs_33 = "2013-06-06";
ljs_33 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_33, ctx) : WAVE.strEscapeHTML(ljs_33);
ljs_32.setAttribute('value', ljs_33);
var ljs_34 = "date";
ljs_34 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_34, ctx) : WAVE.strEscapeHTML(ljs_34);
ljs_32.setAttribute('type', ljs_34);
ljs_30.appendChild(ljs_32);
var ljs_35 = document.createElement('input');
var ljs_36 = "234.11";
ljs_36 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_36, ctx) : WAVE.strEscapeHTML(ljs_36);
ljs_35.setAttribute('value', ljs_36);
var ljs_37 = "text";
ljs_37 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_37, ctx) : WAVE.strEscapeHTML(ljs_37);
ljs_35.setAttribute('type', ljs_37);
ljs_30.appendChild(ljs_35);
var ljs_38 = document.createElement('input');
var ljs_39 = "234.11";
ljs_39 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_39, ctx) : WAVE.strEscapeHTML(ljs_39);
ljs_38.setAttribute('value', ljs_39);
var ljs_40 = "number";
ljs_40 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_40, ctx) : WAVE.strEscapeHTML(ljs_40);
ljs_38.setAttribute('type', ljs_40);
ljs_30.appendChild(ljs_38);
ljs_1.appendChild(ljs_30);
var ljs_41 = document.createElement('div');
var ljs_42 = "container";
ljs_42 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_42, ctx) : WAVE.strEscapeHTML(ljs_42);
ljs_41.setAttribute('id', ljs_42);
var ljs_43 = document.createElement('h1');
var ljs_44 = "Animation Test";
ljs_44 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_44, ctx) : WAVE.strEscapeHTML(ljs_44);
ljs_43.innerText = ljs_44;
ljs_41.appendChild(ljs_43);
var ljs_45 = document.createElement('button');
var ljs_46 = "Highlight";
ljs_46 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_46, ctx) : WAVE.strEscapeHTML(ljs_46);
ljs_45.innerText = ljs_46;
var ljs_47 = "highlight";
ljs_47 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_47, ctx) : WAVE.strEscapeHTML(ljs_47);
ljs_45.setAttribute('class', ljs_47);
ljs_45.addEventListener('click', function() { hello('highlight'); }, false);
ljs_41.appendChild(ljs_45);
var ljs_48 = document.createElement('button');
var ljs_49 = "Fade";
ljs_49 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_49, ctx) : WAVE.strEscapeHTML(ljs_49);
ljs_48.innerText = ljs_49;
var ljs_50 = "fade";
ljs_50 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_50, ctx) : WAVE.strEscapeHTML(ljs_50);
ljs_48.setAttribute('class', ljs_50);
ljs_48.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_48);
var ljs_51 = document.createElement('button');
var ljs_52 = "Rizzle";
ljs_52 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_52, ctx) : WAVE.strEscapeHTML(ljs_52);
ljs_51.innerText = ljs_52;
var ljs_53 = "rizzle";
ljs_53 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_53, ctx) : WAVE.strEscapeHTML(ljs_53);
ljs_51.setAttribute('class', ljs_53);
ljs_51.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_51);
var ljs_54 = document.createElement('button');
var ljs_55 = "Knit";
ljs_55 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_55, ctx) : WAVE.strEscapeHTML(ljs_55);
ljs_54.innerText = ljs_55;
var ljs_56 = "knit";
ljs_56 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_56, ctx) : WAVE.strEscapeHTML(ljs_56);
ljs_54.setAttribute('class', ljs_56);
ljs_54.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_54);
var ljs_57 = document.createElement('button');
var ljs_58 = "Shrink";
ljs_58 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_58, ctx) : WAVE.strEscapeHTML(ljs_58);
ljs_57.innerText = ljs_58;
var ljs_59 = "shrink";
ljs_59 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_59, ctx) : WAVE.strEscapeHTML(ljs_59);
ljs_57.setAttribute('class', ljs_59);
ljs_57.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_57);
var ljs_60 = document.createElement('button');
var ljs_61 = "Rotate";
ljs_61 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_61, ctx) : WAVE.strEscapeHTML(ljs_61);
ljs_60.innerText = ljs_61;
var ljs_62 = "rotate";
ljs_62 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_62, ctx) : WAVE.strEscapeHTML(ljs_62);
ljs_60.setAttribute('class', ljs_62);
ljs_60.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_60);
var ljs_63 = document.createElement('button');
var ljs_64 = "Boom";
ljs_64 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_64, ctx) : WAVE.strEscapeHTML(ljs_64);
ljs_63.innerText = ljs_64;
var ljs_65 = "boom";
ljs_65 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_65, ctx) : WAVE.strEscapeHTML(ljs_65);
ljs_63.setAttribute('class', ljs_65);
ljs_63.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_63);
var ljs_66 = document.createElement('button');
var ljs_67 = "Squeeze";
ljs_67 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_67, ctx) : WAVE.strEscapeHTML(ljs_67);
ljs_66.innerText = ljs_67;
var ljs_68 = "squeeze";
ljs_68 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_68, ctx) : WAVE.strEscapeHTML(ljs_68);
ljs_66.setAttribute('class', ljs_68);
ljs_66.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_66);
var ljs_69 = document.createElement('button');
var ljs_70 = "Deform";
ljs_70 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_70, ctx) : WAVE.strEscapeHTML(ljs_70);
ljs_69.innerText = ljs_70;
var ljs_71 = "deform";
ljs_71 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_71, ctx) : WAVE.strEscapeHTML(ljs_71);
ljs_69.setAttribute('class', ljs_71);
ljs_69.addEventListener('click', hello, false);
ljs_41.appendChild(ljs_69);
ljs_1.appendChild(ljs_41);
var ljs_72 = document.createElement('h1');
var ljs_73 = "Compiler output example";
ljs_73 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_73, ctx) : WAVE.strEscapeHTML(ljs_73);
ljs_72.innerText = ljs_73;
ljs_1.appendChild(ljs_72);
var ljs_74 = document.createElement('code');
var ljs_75 = "      function noRoot() {        var ljs_useCtx = WAVE.isObject(ctx);        var ljs_1 = document.createElement('section');        var ljs_2 = 'sect';        ljs_1.setAttribute('id', ljs_useCtx ? WAVE.strHTMLTemplate(ljs_2, ctx) : WAVE.strEscapeHTML(ljs_2));        var ljs_3 = 'sect';        ljs_1.setAttribute('class', ljs_useCtx ? WAVE.strHTMLTemplate(ljs_3, ctx) : WAVE.strEscapeHTML(ljs_3));        var ljs_4 = ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sollicitudin interdum,      sollicitudin condimentum montes nulla bibendum aliquam velit? Fermentum mattis aenean nec...      Orci proin litora nec ullamcorper?    ';        ljs_1.innerText = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_4, ctx) : WAVE.strEscapeHTML(ljs_4);        if (typeof(root) !== 'undefined' && root !== null) {        if (WAVE.isString(root))        root = WAVE.id(root);        if (WAVE.isObject(root))        root.appendChild(ljs_1);      }    ";
ljs_75 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_75, ctx) : WAVE.strEscapeHTML(ljs_75);
ljs_74.innerText = ljs_75;
ljs_1.appendChild(ljs_74);
if (typeof(root) !== 'undefined' && root !== null) {
if (WAVE.isString(root))
root = WAVE.id(root);
if (WAVE.isObject(root))
root.appendChild(ljs_1);
}
}


function noRoot() {
var ljs_useCtx = WAVE.isObject(ctx);
var ljs_1 = document.createElement('section');
var ljs_2 = "      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sollicitudin interdum,      sollicitudin condimentum montes nulla bibendum aliquam velit? Fermentum mattis aenean nec...      Orci proin litora nec ullamcorper?    ";
ljs_2 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_2, ctx) : WAVE.strEscapeHTML(ljs_2);
ljs_1.innerText = ljs_2;
var ljs_3 = "sect";
ljs_3 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_3, ctx) : WAVE.strEscapeHTML(ljs_3);
ljs_1.setAttribute('id', ljs_3);
var ljs_4 = "sect";
ljs_4 = ljs_useCtx ? WAVE.strHTMLTemplate(ljs_4, ctx) : WAVE.strEscapeHTML(ljs_4);
ljs_1.setAttribute('class', ljs_4);
if (typeof(root) !== 'undefined' && root !== null) {
if (WAVE.isString(root))
root = WAVE.id(root);
if (WAVE.isObject(root))
root.appendChild(ljs_1);
}
}